### ISSUE TITLE
Redux Integration

### ISSUE THREAD

**Issue by destiny-ross-dev** [chingu-voyages/doggo-playdate-tinder#17]
Make a new redux directory in the client's src folder. Add redux and react-redux as dependencies and create root and user reducers and store for the application. Create actions to register and login, and logout the user. Using redux-promise-middleware, redux-thunk or equivalent solution produce asynchronous code that can be sent to the backend with login or registration information and return with a user object. It is ok to mock a response, instead, if the backend has not been set up yet.

**Comment by noi5e** [comment]
I can work on this issue. I actually know next to DIDDLY SQUAT about Redux, so this will be a learning experience for me. Will probably have to ask for help from you all.
