### ISSUE TITLE
Restructure Redux so that it uses loading reducers

### ISSUE THREAD

**Issue by noi5e** [chingu-voyages/doggo-playdate-tinder#24]
This issue's up for discussion when we have time.

Refer to this article from sami: https://medium.com/stashaway-engineering/react-redux-tips-better-way-to-handle-loading-flags-in-your-reducers-afda42a804c6

**Comment by bassamkdev** [comment]
I believe it’s kinda refactoring topic, doesn’t have any functional effect on our app. Let’s leave it for now till we build our MVP

**Comment by noi5e** [comment]
Yep, totally agree. I think the 'icebox' section is for these kinds of issues so I put it here for after the MVP.
